name: crowdhandler_flutter_example
description: Example app for the crowdhandler_flutter package

environment:
  sdk: '^3.6.0'  # Add this to specify the Dart/Flutter SDK version range

dependencies:
  flutter:
    sdk: flutter

  crowdhandler_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
